Remove the arch paramter from option
product-definition-center/pdc-client pull request #109
Opened 2017-07-28 05:59 UTC by xiangge

Remove the arch paramter from option.

JIRA: PDC-2076

2017-07-28 13:54 UTC, hluk requested changes
paramter -> parameter

2017-07-28 13:54 UTC, hluk commented on pdc_client/plugins/release_variant.py
> +            required_args.pop("arch")
Argument `exclude` is not very clear. Perhaps:

```python
if requires_arg_arch:
    required_args["arch"] = {"action": "append", "dest": "arches"}
```

2017-07-31 05:48 UTC, xiangge commented on pdc_client/plugins/release_variant.py
> +            required_args.pop("arch")
I was thinking about maybe some parameters also need to pop in the future, so just use the exclude here.
Anyway, use exclude_arches to instead now.

2017-07-31 06:36 UTC, hluk approved these changes

2017-07-31 07:57 UTC, simozhan commented
LGTM

2017-07-31 08:02 UTC, merged